serverName = "IP change detect"
serverVersion = 0
serverIdentityLength = 20
serverListenAddress = None
serverPort = 65432
clientReconnectInterval = 1
clientRetryMaxCountOnDisconnect = 5
presharedKey = "9IGFWa9hcKmtbh0CNsdj"
socketBufferLength = 1024
dnsResolver = None
dnsRecord = None
dnsRecordType = "A"
internetAliveServer = None
internetAliveQuery = None
