serverName = "IP change detect"
serverVersion = 0
serverIdentityLength = 20
serverListenAddress = None
serverPort = 65432
serverMaxConnection = 10
clientSocketTimeout = 3
clientReconnectInterval = 1
clientRetryMaxCountOnDisconnect = 5
clientTimeoutMaxCountOnDisconnect = 5
clientJsonDecodeErrorMaxCountOnDisconnect = 5
keepaliveAfterIdleSec = 60
keepaliveIntervalSec = 0
keepaliveMaxFails = 0
debugServerFixIdentity = False
debugClientConnectToListenAddress = False
presharedKey = "9IGFWa9hcKmtbh0CNsdj"
socketBufferLength = 1024
dnsResolver = None
dnsRecord = None
dnsRecordType = "A"
internetAliveServer = None
internetAliveQuery = None
useCloudflare = False
cloudflareApiToken = None
cloudflareZoneName = None
externalActionOnIpChange = "ping.exe 1.1.1.1"
